export const minButtonLables = [
  "Money",
  "Dragon",
  "Ghost",
  "USA",
  "Poison",
  "Space",
  "3D",
  "Mouse",
  "Pets",
  "Mobile",
  "Computer",
  "India",
  "Nature",
  "Ocean",
  "Fire",
  "Love",
  "Robot",
  "Night",
  "Dream",
  "Music",
  "Sky",
  "Stars",
  "City",
  "Sun",
  "Moon",
  "Art",
  "Fashion",
  "Food",
  "Games",
  "Speed",
  "Future",
  "Light",
  "Dark",
  "Tech",
  "Cloud",
  "Rain",
  "Water",
  "Earth",
  "Flower",
  "Bird",
  "Dog",
  "Cat",
  "Fish",
  "Wolf",
  "Tiger",
  "Bear",
  "Horse",
  "Snake",
  "Gold",
  "Silver",
  "Bronze",
  "Warrior",
  "Sword",
  "Shield",
  "Magic",
  "Alien",
  "Planet",
  "Rocket",
  "Smoke",
  "Lava",
  "Crystal",
  "Virus",
  "Cyber",
  "Hacker",
  "Matrix",
  "Neon",
  "Pixel",
  "Code",
  "Ninja",
  "Samurai",
  "Temple",
  "Mountain",
  "Desert",
  "Forest",
  "Jungle",
  "River",
  "Lake",
  "Cave",
  "Train",
  "Car",
  "Plane",
  "Boat",
  "Bridge",
  "Tower",
  "Castle",
  "Village",
  "Zombie",
  "Vampire",
  "Witch",
  "Wizard",
  "Time",
  "Clock",
  "Mirror",
  "Shadow",
  "Snow",
  "Ice",
  "Storm",
  "Energy",
  "Vibe",
  "Noise",
];

export const placeholders = ["Dog", "Cycle", "Mountain", "Driving", "Hospital"];

export const images = [
  "./images/wallpaper1.jpg",
  "./images/wallpaper2.jpg",
  "./images/wallpaper3.jpg",
];

export const button = {
  buttonLabels: [
    "Sky",
    "Wallpaper",
    "Girl",
    "piersi",
    "man",
    "Urban",
    "Earth",
    "Tokyo",
    "Heart",
  ],
};

export const message: string[] = [
  "Ask OpenImage Catalogue Anything",
  "Download High-Quality Images Easily",
  "Batch Download With One Click",
  "Edit And Enhance Images With AI",
  "Simple, Fast, And User-Friendly",
];

export const maxRetryError = "Max retries exceeded while fetching Openverse images.";

export const slowLoadingWarning = "First load may be slow due to Netlify free hosting. Please reload — we’ll fix this soon.";

export const breakpointColumnsObj = {
    default: 4,
    1100: 3,
    700: 2,
    500: 1,
  };
