# This workflow will build a React project

name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        if: steps.check_changes.outputs.run == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        if: steps.check_changes.outputs.run == 'true'
        run: npm install

      - name: Run React build
        if: steps.check_changes.outputs.run == 'true'
        run: npm run build

#      - name: Run React tests
#        if: steps.check_changes.outputs.run == 'true'
#        run: npm test -- --watchAll=false

      - name: Skip React workflow (no relevant changes)
        if: steps.check_changes.outputs.run == 'false'
        run: echo "No changes in DownloaderModule-Web or node.js.yml. Skipping React build/test."
